CREATE TABLE employees (
                           id BIGSERIAL PRIMARY KEY,
                           first_name VARCHAR(100) NOT NULL,
                           last_name VARCHAR(100) NOT NULL,
                           pesel VARCHAR(11) NOT NULL UNIQUE,
                           email VARCHAR(255) NOT NULL UNIQUE,
                           phone_number VARCHAR(20),
                           date_of_birth DATE NOT NULL,
                           hire_date DATE NOT NULL,
                           termination_date DATE,
                           salary DECIMAL(10, 2) NOT NULL,
                           position_level VARCHAR(50) NOT NULL,
                           department VARCHAR(50) NOT NULL,
                           employment_type VARCHAR(50),
                           status VARCHAR(50),
                           street VARCHAR(255),
                           city VARCHAR(255),
                           postal_code VARCHAR(255),
                           country VARCHAR(255),
                           bank_account_number VARCHAR(255),
                           bank_name VARCHAR(255),
                           tax_id VARCHAR(255),
                           name VARCHAR(255),
                           phone VARCHAR(255),
                           relation VARCHAR(255),
                           created_at TIMESTAMP NOT NULL,
                           updated_at TIMESTAMP NOT NULL,
                           created_by VARCHAR(100),
                           updated_by VARCHAR(100)
);