spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: employee-service
              uri: lb://employee-service
              predicates:
                - Path=/api/employees/**
              filters:
                - StripPrefix=2

            - id: project-service
              uri: lb://project-service
              predicates:
                - Path=/api/projects/**
              filters:
                - StripPrefix=2

            - id: notification-service
              uri: lb://notification-service
              predicates:
                - Path=/api/notifications/**
              filters:
                - StripPrefix=2

          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

          globalcors:
            cors-configurations:
              '[/**]':
                allowed-origins:
                  - "http://localhost:4200"
                allowed-methods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                  - PATCH
                allowed-headers: "*"
                allow-credentials: true
                max-age: 3600

          httpclient:
            connect-timeout: 5000
            response-timeout: 10s

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

info:
  app:
    name: API Gateway
    description: Automation Company Management System - API Gateway
    version: 0.0.1-SNAPSHOT

logging:
  level:
    org.springframework.cloud.gateway: INFO
    reactor.netty.http.client: INFO

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    urls:
      - name: employee-service
        url: /api/employees/v3/api-docs
      - name: project-service
        url: /api/projects/v3/api-docs
      - name: notification-service
        url: /api/notifications/v3/api-docs
