FROM quay.io/keycloak/keycloak:26.0.5

COPY ./realm-export.json /opt/keycloak/data/import/realm-export.json

ENV KC_HTTP_ENABLED=true
ENV KC_HEALTH_ENABLED=true
ENV KC_HOSTNAME_STRICT=false

ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
CMD ["start", "--import-realm"]